// Actions auditées obligatoirement (format SCREAMING_SNAKE_CASE)
// Ajouter ici toute nouvelle action sensible

export const AuditActions = {
  // Contrats
  CONTRACT_CREATED: 'CONTRACT_CREATED',
  CONTRACT_ACTIVATED: 'CONTRACT_ACTIVATED',
  CONTRACT_SUSPENDED: 'CONTRACT_SUSPENDED',
  CONTRACT_CLOSED: 'CONTRACT_CLOSED',

  // Charges
  CHARGE_CREATED: 'CHARGE_CREATED',
  CHARGE_VALIDATED: 'CHARGE_VALIDATED',
  CHARGE_REJECTED: 'CHARGE_REJECTED',
  CHARGE_ADDED_TO_CONTRACT: 'CHARGE_ADDED_TO_CONTRACT',

  // Caution
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_VALIDATED: 'DEPOSIT_VALIDATED',
  DEPOSIT_PAID: 'DEPOSIT_PAID',
  DEPOSIT_USED: 'DEPOSIT_USED',
  DEPOSIT_REFUNDED: 'DEPOSIT_REFUNDED',

  // Paiements
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',

  // Reprises
  REPOSSESSION_PROPOSED: 'REPOSSESSION_PROPOSED',
  REPOSSESSION_SM_VALIDATED: 'REPOSSESSION_SM_VALIDATED',
  REPOSSESSION_ADMIN_APPROVED: 'REPOSSESSION_ADMIN_APPROVED',

  // Véhicule
  VEHICLE_STATUS_CHANGED: 'VEHICLE_STATUS_CHANGED',
  VEHICLE_IMMOBILIZED: 'VEHICLE_IMMOBILIZED',
  VEHICLE_RELEASED: 'VEHICLE_RELEASED',

  // Chauffeur
  DRIVER_STATUS_CHANGED: 'DRIVER_STATUS_CHANGED',
  DRIVER_BLACKLISTED: 'DRIVER_BLACKLISTED',
  DRIVER_KYC_VALIDATED: 'DRIVER_KYC_VALIDATED',
  DRIVER_FIELD_VALIDATED: 'DRIVER_FIELD_VALIDATED',

  // Finance
  PENALTY_VALIDATED: 'PENALTY_VALIDATED',

  // Permissions
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',

  // Relevés
  SETTLEMENT_APPROVED: 'SETTLEMENT_APPROVED',
  SETTLEMENT_PAID: 'SETTLEMENT_PAID',
} as const;

/** @deprecated Utilisez AuditActions */
export const AuditAction = AuditActions;

export type AuditActionType = (typeof AuditActions)[keyof typeof AuditActions];
