// Actions auditées obligatoirement (format SCREAMING_SNAKE_CASE)
// Ajouter ici toute nouvelle action sensible

export const AuditActions = {
  // Contrats
  CONTRACT_CREATED: 'CONTRACT_CREATED',
  CONTRACT_ACTIVATED: 'CONTRACT_ACTIVATED',
  CONTRACT_SUSPENDED: 'CONTRACT_SUSPENDED',
  CONTRACT_CLOSED: 'CONTRACT_CLOSED',

  // Charges
  CHARGE_CREATED: 'CHARGE_CREATED',
  CHARGE_VALIDATED: 'CHARGE_VALIDATED',
  CHARGE_REJECTED: 'CHARGE_REJECTED',
  CHARGE_ADDED_TO_CONTRACT: 'CHARGE_ADDED_TO_CONTRACT',

  // Caution
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_VALIDATED: 'DEPOSIT_VALIDATED',
  DEPOSIT_PAID: 'DEPOSIT_PAID',
  DEPOSIT_USED: 'DEPOSIT_USED',
  DEPOSIT_REFUNDED: 'DEPOSIT_REFUNDED',

  // Paiements
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',

  // Reprises
  REPOSSESSION_PROPOSED: 'REPOSSESSION_PROPOSED',
  REPOSSESSION_SM_VALIDATED: 'REPOSSESSION_SM_VALIDATED',
  REPOSSESSION_ADMIN_APPROVED: 'REPOSSESSION_ADMIN_APPROVED',

  // Véhicule
  VEHICLE_STATUS_CHANGED: 'VEHICLE_STATUS_CHANGED',
  VEHICLE_IMMOBILIZED: 'VEHICLE_IMMOBILIZED',
  VEHICLE_RELEASED: 'VEHICLE_RELEASED',

  // Chauffeur
  DRIVER_STATUS_CHANGED: 'DRIVER_STATUS_CHANGED',
  DRIVER_BLACKLISTED: 'DRIVER_BLACKLISTED',
  DRIVER_KYC_VALIDATED: 'DRIVER_KYC_VALIDATED',
  DRIVER_FIELD_VALIDATED: 'DRIVER_FIELD_VALIDATED',

  // Finance
  PENALTY_VALIDATED: 'PENALTY_VALIDATED',

  // Permissions
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',

  // Relevés
  SETTLEMENT_APPROVED: 'SETTLEMENT_APPROVED',
  SETTLEMENT_PAID: 'SETTLEMENT_PAID',

  // Documents (Phase 3-B)
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',

  // Inspections (Phase 3-B)
  INSPECTION_CREATED: 'INSPECTION_CREATED',
  INSPECTION_DRIVER_SIGNED: 'INSPECTION_DRIVER_SIGNED',
  INSPECTION_MANAGER_SIGNED: 'INSPECTION_MANAGER_SIGNED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',

  // Incidents (Phase 3-B)
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  INCIDENT_CLOSED: 'INCIDENT_CLOSED',

  // Accidents (Phase 3-B)
  ACCIDENT_DECLARED: 'ACCIDENT_DECLARED',
  ACCIDENT_STEP_ADVANCED: 'ACCIDENT_STEP_ADVANCED',
  ACCIDENT_EXPENSE_VALIDATED: 'ACCIDENT_EXPENSE_VALIDATED',
  ACCIDENT_CLOSED: 'ACCIDENT_CLOSED',

  // Maintenance (Phase 3-B)
  MAINTENANCE_CREATED: 'MAINTENANCE_CREATED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',

  // Immobilisations (Phase 3-B / 3-C)
  IMMOBILIZATION_STARTED: 'IMMOBILIZATION_STARTED',
  IMMOBILIZATION_ENDED: 'IMMOBILIZATION_ENDED',

  // Absences spéciales (Phase 3-C)
  SPECIAL_ABSENCE_REQUESTED: 'SPECIAL_ABSENCE_REQUESTED',
  SPECIAL_ABSENCE_APPROVED: 'SPECIAL_ABSENCE_APPROVED',
  SPECIAL_ABSENCE_REJECTED: 'SPECIAL_ABSENCE_REJECTED',
  SPECIAL_ABSENCE_CANCELLED: 'SPECIAL_ABSENCE_CANCELLED',

  // Carburant (Phase 3-C)
  FUEL_RECORDED: 'FUEL_RECORDED',
  FUEL_VALIDATED: 'FUEL_VALIDATED',

  // Portail propriétaire (Phase 3-C)
  OWNER_VISIBILITY_CONFIGURED: 'OWNER_VISIBILITY_CONFIGURED',
  OWNER_PAYMENT_RECORDED: 'OWNER_PAYMENT_RECORDED',

  // Disponibilité (Phase 3-C)
  AVAILABILITY_EVENT_RECORDED: 'AVAILABILITY_EVENT_RECORDED',
  AVAILABILITY_EVENT_RESOLVED: 'AVAILABILITY_EVENT_RESOLVED',
} as const;

/** @deprecated Utilisez AuditActions */
export const AuditAction = AuditActions;

export type AuditActionType = (typeof AuditActions)[keyof typeof AuditActions];
